In [1]:
import numpy as np

In [3]:
#first_numpy_array
first_numpy_array=np.array([1,2,4,5])

In [4]:
#print array
print(first_numpy_array)

[1 2 4 5]


In [5]:
#array with zeros
np.zeros(3)

array([0., 0., 0.])

In [10]:
#array with ones
np.ones([8,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
#empty array
empty_array=np.empty([3,3])
empty_array

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.69163624e-321],
       [1.11261027e-306, 1.69120688e-306, 2.56765117e-312]])

In [15]:
#range array
array_range=np.arange(12)
print(array_range)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
#reshape method to change/create array
array_range.reshape([3,4])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
#linspace for linearly(equal) spaced data elements
linespace_array=np.linspace(2,8,5)
linespace_array

array([2. , 3.5, 5. , 6.5, 8. ])

In [29]:
#oneDimensional_array
oneD_array=np.arange(15)

In [30]:
#print oneD_array
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [32]:
#two dimensional array
twoD_array=oneD_array.reshape(3,5)

In [33]:
#print two dimensional array
print(twoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [34]:
#Three dimensional Array
ThreeD_array=np.arange(27).reshape(3,3,3)

In [35]:
ThreeD_array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])